name: CI

on: [push, pull_request]

jobs:
  compile:
    name: Check format and compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '23.3'
          elixir-version: '1.11'

      - name: Install dependencies
        run: mix deps.get

      - name: Check format
        run: mix format --check-formatted

      - name: Compile with warnings as errors
        run: mix compile --warnings-as-errors

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '23.3'
          elixir-version: '1.11'

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run tests with coverage
        run: mix coveralls.github
